controller:

    # Replaces the default nginx-controller image with a custom image that contains the Signal Sciences nginx Module
    image:
      repository: ubbleai/nginx-ingress-controller
      tag: "0.25.1"
      pullPolicy: IfNotPresent

    # Loads a custom nginx template with the Signal Sciences Lua directives included 
    customTemplate:
      configMapName: "sigsci-nginx-template"
      configMapKey: "nginx.tmpl"

    # Loads sidecar container image that houses the Signal Sciences Agent
    extraContainers:
      - name: sigsci-agent
        image: ubbleai/sigsci-agent:4.0.0
        imagepullPolicy: IfNotPresent
        volumeMounts:
        - name: sigsci-socket
          mountPath: /var/run

        # Sets Signal Sciences Agent keys
        env:
        - name: SIGSCI_ACCESSKEYID
          value: ${sigsci_accesskeyid}
        - name: SIGSCI_SECRETACCESSKEY
          value: ${sigsci_secretaccesskey}

    # Mounts shared volume for sigsci.sock file
    extraVolumeMounts:
      - name: sigsci-socket
        mountPath: /var/run

    extraVolumes:
      - name: sigsci-socket
        emptyDir: {}
